application: tv-addicts
version: 1
runtime: python27
api_version: 1
threadsafe: false
builtins:
- remote_api: on
handlers:
- url: /.*
  script: main.app
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
